name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: cd ml_project && flake8 .

  test:
    name: Test /predict endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd ml_project
          pip install -r requirements.txt
          pip install pytest requests

      - name: Run test for predict endpoint
        run: |
          cd ml_project
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl -X POST "http://localhost:8000/predict" -H "Content-Type: application/json" -d '{"model_name": "model", "features": [1, 2, 3, 4, 5]}'

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mlops-domestic-abuse-api:latest ./ml_project
